- src/data/repositories/SurveyFormD2Repository.ts
- src/data/repositories/UserD2Repository.ts
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/domain/entities/TablePagination.ts
- src/domain/repositories/SurveyRepository.ts
- src/domain/usecases/GetAllSurveysUseCase.ts
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/SurveyListTable.tsx
- src/webapp/hooks/useSurveys.ts
-   **Issue:** Closes [add pagination](https://app.clickup.com/t/862km53ey)
- Added pagination to all surveys lists
> Add pagination to surveys lists

- src/domain/entities/AMRSurveyModule.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/__tests__/moduleFixtures.ts
- src/domain/usecases/ApplyInitialRulesToSurveyUseCase.ts
- src/domain/usecases/GetAllAccesibleModulesUseCase.ts
- src/domain/usecases/GetSurveyUseCase.ts
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes https://app.clickup.com/t/8693rkzwt
1. Based on the rules defined in datastore for each parent survey instance, apply HIDEFIELD/HIDESECTION rule for each child form.
2. refactor code in src/domain/usecases/GetSurveyUseCase.ts to break up into functions.
NOTE : datastore structure for survey rules
```
"rulesBySurvey": [
{
"surveyId": "p91asa2vebZ",
"surveyRules": [
{
"formId": "mesnCzaLc7u",
"rules": [
{
"id": "1",
"toHide": [
"SCYImStXDHM"
],
"type": "HIDEFIELD"
},
{
"id": "2",
"toHide": [
"mIHOCwjHtyu"
],
"type": "HIDESECTION"
}
]
}
]
}
],
```
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/1c200566-dabf-4e43-aa9a-b40910448c93
> feat: hide field/section for a given survey from rule in datastore

- i18n/en.pot
- src/data/entities/D2Program.ts
- src/data/entities/D2Survey.ts
- src/data/repositories/SurveyFormD2Repository.ts
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/data/utils/questionHelper.ts
- src/data/utils/surveyFormMappers.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
- src/domain/usecases/ApplyInitialRulesToSurveyUseCase.ts
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/SurveySection.tsx
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes #?https://app.clickup.com/t/8693rygwd
- 8693rygwd
1. Remove unused custom repeat data element logic.
2. Fetch if a stage is repeatable from dhis api
3. For repeatable stages, show add/remove buttons in survey. 
4. Save repeated stages to DHIS
5. Parse repeatable stages and display for existing surveys. 
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/6896a4a2-5df2-4eef-b7a5-d955f87617e4
> Repeatable program stages 

- i18n/es.po
- src/domain/entities/Program.ts
- src/domain/usecases/GetChildCountUseCase.ts
- src/domain/utils/PPSProgramsHelper.ts
- src/domain/utils/optionsHelper.ts
- src/webapp/components/action-menu-button/ActionMenuButton.tsx
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/hook/useSurveyListActions.ts
- src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
- src/webapp/components/survey-list/table/SurveyListTable.tsx
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/SurveySection.tsx
- src/webapp/components/survey/hook/useCaptureAccess.ts
- src/webapp/components/survey/hook/useReadAccess.ts
- src/webapp/components/survey/hook/useReadOnlyAccess.ts
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes #8693zgcet [Read only functionality](https://app.clickup.com/t/8693zgcet)
- Create a read-only functionality based on the User's group: If he belongs to the module's read access group and not capture and admin groups, he only has read access. The menu items that are capture related are hidden (create/delete), and replaced with a "view" option, that leads to the survey with disabled fields and save button.
[screen-capture (3).webm](https://github.com/EyeSeeTea/amr-surveys/assets/44171664/1548310d-a697-40a7-a76c-6952d61c46c1)
- Create a user with a module's read access group and another with it, and check the behaviour of each.
> Read only functionality

- src/webapp/contexts/CurrentModuleContextProvider.tsx
-   **Issue:** Closes#86948jvz2 [Fix module context on the first list of each module](https://app.clickup.com/t/86948jvz2)
- Use session storage to persist currentModule within page refreshes
> Persist currentModule context within page refresh

- i18n/en.pot
- i18n/es.po
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/data/utils/questionHelper.ts
- src/data/utils/surveyFormMappers.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
- src/webapp/components/survey-questions/QuestionWidget.tsx
- src/webapp/components/survey-questions/widgets/SearchableSelect.tsx
- src/webapp/components/survey-questions/widgets/TextWidget.tsx
- src/webapp/components/survey/GridRow.tsx
- src/webapp/components/survey/GridSection.tsx
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/SurveySection.tsx
- src/webapp/components/survey/hook/useGridRow.ts
- src/webapp/components/survey/hook/useGridSection.ts
- src/webapp/components/survey/hook/useSurveyForm.ts
- src/webapp/hooks/useASTGuidelinesOptions.ts
-   **Issue:** Closes #?https://app.clickup.com/t/8694ap44d
- https://app.clickup.com/t/8694ap48n
- 8694ap44d
- 8694ap48n
1. On species change, pre populate all antibiotic options in grid
2. handle AST Result or Value data entry
3. On reset of species, reset antibiotic details.
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/5d50d20c-19b5-4863-a5c6-d4bdc5b762a9
> Show Antibiotics in grid format and auto populate antibiotics on species select

- src/data/repositories/SurveyFormD2Repository.ts
-   **Issue:** Closes #8693jgah5 [Parse IDs in error messages](https://app.clickup.com/t/8693jgah5)
- Parse dataElements, orgUnits & Program Id's in error messages, and get their short names to display on the error message.
- Prevalence -> create new facility and add a orgUnit not matching with Program orgUnit
> Error messages with names

- src/webapp/components/survey-questions/widgets/DateTimePickerWidget.tsx
-   **Issue:** Closes # [For day and time pickers convert them to 24h instead of AM/PM](https://app.clickup.com/t/8694grg6n)
- use datepicker flag to use 24h time
> DateTime picker 24h instead of AM PM

- src/data/utils/surveyListMappers.ts
- src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/8694hemdy
- 8694hemdy
1. For all children of case report form, show patient id coulmn.
Couple of examples :
> show patient id column for all children of case report form

- src/data/repositories/SurveyFormD2Repository.ts
- src/data/utils/questionHelper.ts
- src/webapp/components/survey-questions/QuestionWidget.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/8694grcdn
- 8694grcdn
apply sort order for event program fields.
> fix: fix order of fields for event programs

- src/CompositionRoot.ts
- src/data/repositories/PaginatedSurveyD2Repository.ts
- src/data/repositories/testRepositories/PaginatedSurveyTestRepository.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireRules.ts
- src/domain/repositories/PaginatedSurveyRepository.ts
- src/domain/usecases/GetAllSurveysUseCase.ts
- src/domain/usecases/GetFilteredPPSPatientsUseCase.ts
- src/domain/usecases/GetFilteredPrevalencePatientsUseCase.ts
- src/domain/usecases/GetPaginatedSurveysUseCase.ts
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/hook/usePatientSearch.ts
-   **Issue:** Closes #?https://app.clickup.com/t/8694afm42
- 8694afm42
Search for prevalence patients and some perf improvements
> Search for prevalence patients and some perf improvements

- src/data/repositories/SurveyFormD2Repository.ts
- src/domain/entities/Questionnaire/QuestionnaireRules.ts
-   **Issue:** Closes #8694nyekv, #8694nyekv    
-   https://app.clickup.com/t/8694nyekv, https://app.clickup.com/t/8694nyekv
1. Fix order of questions for program stages with sections.
2. Fix program rule parsing for not condition inside parenthesis. 
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/790da705-46f7-44bb-b30f-0d0a0d8483ac
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/4384bbe8-5099-4881-8e4c-2075cb74de3d
the program rule condition had an extra parenthesis () around condition : (#{AMR_CRF_PRV_IF_NO_INDICATE_PERIOD_BETWEEN_SAMPLING_LAST_AB_TAKE})
We need to remove this. Updated program rule : https://dev.eyeseetea.com/who-dev-238/api/programRules/cdplJvEChSz.json
> fix : antiobiotc history order and program rule fix

- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
-   **Issue:** Closes #https://app.clickup.com/t/869569t5u, #869569t5u
1. When questions are hidden as side effect of another question update, reset their values
IMPORTANT NOTE : 
Following metadata change is required to program rule : 
https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/programSection/programRule/cdplJvEChSz
Hide field "Add another one"
Uploading ResetFieldsOnNo-Intermediate.mov…
> clear field option change - intermediate fix

- src/data/repositories/SurveyFormD2Repository.ts
- src/data/utils/surveyChildCountHelper.ts
-   **Issue:** Closes https://app.clickup.com/t/86961vz1t, #86961vz1t
- https://app.clickup.com/t/869689u3g, #869689u3g
1. Save forms synchronously
2. Fetch child counts with pagination
> fix: paginated child count + sync save

- package.json
- src/data/entities/D2ExpressionParser.ts
- src/data/utils/ruleHelper.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireRules.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
- src/domain/entities/generic/HashMap.ts
- yarn.lock
-   **Issue:** Closes https://app.clickup.com/t/8695pt0av, #8695pt0av
1. Use dhis2 expression parser for parsing program rule conditions
2. Recursively update all survey questions (form field) that need to be updated as a side effect of the current question update
testing videos : https://drive.google.com/drive/folders/1BQkuP6o0fi0GxY-cqbTJzlCAj9Ivk7bu?usp=sharing
> feat:use dhis2 expression parser

- src/webapp/components/survey/SurveyForm.tsx
-   **Issue:** Closes https://app.clickup.com/t/86971bu93
#86971bu93
> feat: move add another treatment button to the bottom of section

- i18n/en.pot
- i18n/es.po
- src/data/utils/questionHelper.ts
- src/data/utils/surveyFormMappers.ts
- src/utils/dates.ts
- src/webapp/components/survey/SurveyForm.tsx
-   **Issue:** Closes https://app.clickup.com/t/8696xt3f5 #8696xt3f5
- Submit Error Handling in `SurveyForm`: in case of an error, the loading state is now set to false, and the user remains in the form page instead of being redirected.
- Invalid Dates: invalid dates from the server are treated as undefined and unset. They will be unset when the form is saved.
- Added try/catch blocks to ensure errors during mapping are caught and handled
https://github.com/user-attachments/assets/585708d9-1bfb-4033-8dac-92bfc0d960a1
- I discovered that the `"DATE_TIME_KNOWN"` string is being used in the program rule `dvlWCs6iKLF`.  
- It may be important to investigate this specific case to ensure that overriding this value to `undefined` doesn't cause unintended issues. If needed, specific handling …
> fix: Indefinite spinner on save survey form error

- src/data/entities/D2ExpressionParser.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireRules.ts
-   **Issue:** Closes https://app.clickup.com/t/8696w4136 #8696w4136
- Disable the fields targeted by an assign action (tracker capture app does the same)
- Use D2ExpressionParser to evaluate the expression used in the action data
- Set the target field values according to the evaluated assign action data
https://github.com/user-attachments/assets/58211b58-e14e-4063-842a-dedd9539b7f5
- While this PR provides generic support for assign actions, I only tested it with the program rule mentioned in the issue
> feat: Add support for ASSIGN actions in Program Rules

- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
-   **Issue:** Closes https://app.clickup.com/t/8697wbx9k #8697wbx9k
- When a program rule with an "assign" action is executed, the Questionnaire needs to be updated again in order to re-evaluate program rules and trigger any other actions depending on the updated value. So a recursive call was added  to `Questionnaire.updateQuestionnaire` when assign rules are executed.
- At first I tried to handle this scenario at the level of `QuestionnaireQuestion.updateQuestions` with its `recursivelyApplySideEffects`, but at that level it is not possible to run the assign action and then run a "hidesection" action. 
- In the testing scenario, the first update is the user triggered action (change date), then the assign action changes "age group", and then the second update triggers the "hidesection" …
> Fix: Propagate program rules execution after assign actions

- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/webapp/components/survey/SurveySection.tsx
- src/webapp/components/survey/TableSection.tsx
-   **Issue:** Closes https://app.clickup.com/t/8697y23cu #8697y23cu
- Added a new `computed` property  to `QuestionnaireQuestion`
- This property is set to `true` when an "assign" action from a program rule sets the question value, otherwise `false`.
- Disable the `QuestionWidget` if `computed` value is true
- Why a new property?
- Allows reverting the "disabled" state in the view
- Prevents unintentionally enabling a field that was disabled due to other conditions 
https://github.com/user-attachments/assets/27240154-091c-49e9-9ccd-85797b89cb96
> fix: disabled state for questions targetted by assign actions

- src/domain/entities/Survey.ts
- src/webapp/components/survey/SurveyFormOUSelector.tsx
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes https://app.clickup.com/t/8697wb707 #8697wb707
- Changed `shouldDisableSave` from state to a memoized value since it's computed
- Added condition to return true if no OrgUnit is selected for `formType === "PrevalenceFacilityLevelForm"`
**UPDATE:**   applied the disable condition to all forms that support org unit selection. For that, extracted to a var `SURVEYS_WITH_ORG_UNIT_SELECTOR`.
https://github.com/user-attachments/assets/5324317f-6f74-40aa-913e-faad93707fba
> Disable save in forms that support Org Unit selection

- src/data/utils/surveyFormMappers.ts
-   **Issue:** Closes https://app.clickup.com/t/869a9cze4 #869a9cze4
Before
https://github.com/user-attachments/assets/330f8a05-8e4c-405c-a9f6-62daf1508c03
After
https://github.com/user-attachments/assets/6736d210-2e02-471f-ad68-28cbb8315ec9
I’ve found the cause of the bug. It’s not a problem with the case report form; it’s a problem with all forms provoked by the app and a bug in dhis2.
I've debugged the core using d2-docker and the current eyeseetea fork branch.
After debug the core I’ve identified the problem.
The problem occurs when we send the payload so:
```json
{
"trackedEntities": [
{
"enrollments": [
{
"attributes": [...],
"events": [...]
}
],
"attributes": [...],
"relationships": [...]
}
]
}
```
The bug is provoked when we send attribute values under enrollment and tracked …
> Send attributes only under tracked entity

- src/data/entities/D2Program.ts
- src/data/repositories/SurveyFormD2Repository.ts
-   **Issue:** Closes https://app.clickup.com/t/869ab1njz #869ab1njz
Before, the programStageDataElements was a key in the root of the response:
```json
{
"ProgramStageDataElements":[],
"ProgramStages":[]
}
```
Now, this key is only under the program Stages. Then It's been necessary:
1 -Change de model types of the response 
2 -Extract programStageDataElements from programStages
```json
{
"ProgramStages":[
{
"programStageDataElements":[]
},
{
"programStageDataElements":[]
},
]
}
```
When I tested, I saw something weird in the form. The order was not how I remembered. 
Analysing the response, I saw that another key is missing now, programTrackedEntityAttributes:
Before, the programTrackedEntityAttributes was also a key in the root of the response:
 
```json
{ …
```
> Fix bug request form in 2.41.5 version

- src/webapp/components/main-layout/MainLayout.tsx
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
- src/webapp/components/survey-list/table/SurveyListTable.tsx
- src/webapp/pages/landing/LandingPage.tsx
-   **Issue:** Closes https://app.clickup.com/t/869agtur3 #869agtur3
No affected changes in forms
No affected changes in desktop
Two main issues were detected:
1 - Distribution of space between Menu and main content
2 - Table rendering on tablets
For the menu, I extended the definition of breakpoints to 4 levels to cover all scenarios: desktop, tablets of different sizes in both landscape and portrait.
For the tables, we need to distinguish between two types:
Normal (survey and facility)
Paginated (case reports, etc. with more columns)
For the normal ones, I set a minimum cell width so that headers don’t get compressed on tablets. A horizontal scroll appears when necessary.
For the paginated ones, there was a configuration that tried to fit all the columns into the table width using …
> Fix design breakpoints and tables in tablet devices

- src/webapp/components/main-layout/MainLayout.tsx
-   **Issue:** Closes https://app.clickup.com/t/869akhcgh #869akhcgh
> Set full width in main component if menu is hidden
