- src/data/repositories/SurveyFormD2Repository.ts
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/domain/entities/Survey.ts
- src/domain/repositories/SurveyRepository.ts
- src/domain/usecases/GetAllSurveysUseCase.ts
- src/webapp/components/survey-list/SurveyList.tsx
> Show associated PPS survey Name for all surveys

- package.json
> feat: rename app

- src/data/entities/D2Survey.ts
- src/data/repositories/PaginatedSurveyD2Repository.ts
- src/data/repositories/SurveyFormD2Repository.ts
- src/data/utils/surveyProgramHelper.ts
- src/domain/usecases/GetAllPrevelancePatientSurveysUseCase.ts
- src/domain/usecases/GetPaginatedPatientSurveysUseCase.ts
- src/domain/utils/PPSProgramsHelper.ts
- src/domain/utils/menuHelper.ts
-   **Issue:** Closes https://app.clickup.com/t/8693jdg52
Fix all Prevalence typos  across code.
**### IMPORTANT NOTE: This code merge needs to be accompanied with datastore typo fix.**
> Fix all Prevalence typos  across code.

- src/webapp/components/survey-questions/QuestionWidget.tsx
- src/webapp/components/survey-questions/widgets/DropdownSelectWidget.tsx
- src/webapp/components/survey-questions/widgets/SearchableSelect.tsx
-   **Issue:** Closes https://app.clickup.com/t/8693brat8
1. Selectable search for dropdown with more than 10 options.
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/b085b8e4-1e46-4dba-8592-b7aa6c63dc62
> feat: searchable select

- src/data/repositories/PaginatedSurveyD2Repository.ts
- src/domain/utils/PPSProgramsHelper.ts
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/hook/usePatientSearch.ts
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/SurveyFormOUSelector.tsx
- src/webapp/hooks/useSurveys.ts
- src/webapp/pages/app/App.tsx
- src/webapp/pages/survey-list/SurveyListPage.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/8693jga70, https://app.clickup.com/t/8693hnt99, https://app.clickup.com/t/8693jgaca
1. Redirect to homepage on survey list or form page, if required state data is not present.
2. Fix page count on patient search
3. Use country short names on OU selector
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/77219639-2b3c-445f-8910-eacfa69730b9
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/05d1d7c2-a21d-475b-a371-647b1379f240
> fix: ou short names, redirect for PPS, better naming refactor

- src/data/utils/surveyListMappers.ts
- src/domain/usecases/ApplyInitialRulesToSurveyUseCase.ts
-   **Issue:** Closes #869470wbn [Error in one of the existing surveys. Facility not loading](https://app.clickup.com/t/869470wbn)
- Fix orgUnit name not showing up on trackedEntities surveys
- Fix survey bug when trying to edit
> Fix OrgUnit name not showing up & fix edit bug

- src/data/repositories/UserD2Repository.ts
- src/webapp/components/survey/SurveyFormOUSelector.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/8694b7q3d
1.  consider ou levels 6,7,8 as hospitals
> consider ou levels 6,7,8 as hospitals

- src/CompositionRoot.ts
- src/data/DataStoreKeys.ts
- src/data/entities/D2Survey.ts
- src/data/repositories/ASTGuidelinesD2Repository.ts
- src/data/repositories/SurveyFormD2Repository.ts
- src/data/repositories/testRepositories/ASTGuidelinesTestRepository.ts
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/data/utils/surveyListMappers.ts
- src/domain/entities/ASTGuidelines.ts
- src/domain/entities/Survey.ts
- src/domain/repositories/ASTGuidelinesRepository.ts
- src/domain/repositories/SurveyRepository.ts
- src/domain/usecases/GetASTGuidelinesUseCase.ts
- src/domain/usecases/SaveFormDataUseCase.ts
- src/webapp/components/survey-list/hook/useSurveyListActions.ts
- src/webapp/contexts/ASTGuidelinesContextProvider.tsx
- src/webapp/contexts/CurrentASTGuidelinesContextProvider.tsx
- src/webapp/contexts/CurrentSurveysContextProvider.tsx
- src/webapp/contexts/ast-guidelines-context.ts
- src/webapp/contexts/current-ast-guidelines-context.ts
- src/webapp/contexts/current-surveys-context.ts
- src/webapp/hooks/useASTGuidelinesOptions.ts
- src/webapp/pages/app/App.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/862kmgx99
- 862kmgx99
1. save custom ast guidelines, based on selection - CLSI Custom, EUCAST custom, empty custom
2. fetch and set current ast guidelines based on survey type
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/d326f235-949a-4e05-9649-0b5016b22ed9
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/0c1c19a5-0f91-4a28-b39a-1fe87510955a
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/5b0bb41d-fceb-4be5-ae2f-183e31cf1d41
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/654ce0d6-6b0e-4d24-94c3-38f6aa81afd5
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/856398cd-0625-4c11-ac65-d291b2848b47
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/81db8ffb-f682-42eb-80fc-f328affcfb6d
> Custom pathogen antibiotic mapping

- src/data/entities/D2Survey.ts
- src/data/utils/surveyListMappers.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Survey.ts
- src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
- src/webapp/components/survey/SurveyForm.tsx
-   **Issue:** Closes #8693zgbgn https://app.clickup.com/t/8693zgbgn
- Fix patient "profile" stage form info not being saved;
- Use "unique survey patient Id" as the patientId on the patient list & remove "patient name" column
- Go to prelavence -> "prevalence survey"'s list facility -> list patients -> edit, edit profile values, check listing.
> Prevalence - Fix patient profile save & listing

- src/data/entities/D2Program.ts
- src/data/repositories/SurveyFormD2Repository.ts
-   **Issue:** Closes #8694fmd8r [Fix order of options in different fields](https://app.clickup.com/t/8694fmd8r)
- Add sortOrder type and use it to sort options in form.
> Sort form options

- i18n/en.pot
- i18n/es.po
- src/CompositionRoot.ts
- src/data/entities/D2Survey.ts
- src/data/repositories/PaginatedSurveyD2Repository.ts
- src/data/repositories/testRepositories/PaginatedSurveyTestRepository.ts
- src/data/utils/surveyListMappers.ts
- src/domain/entities/Survey.ts
- src/domain/repositories/PaginatedSurveyRepository.ts
- src/domain/usecases/GetFilteredPatientsUseCase.ts
- src/domain/usecases/GetPaginatedPatientSurveysUseCase.ts
- src/domain/utils/surveyParentNameHelper.ts
- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/hook/usePatientSearch.ts
- src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/8693uttr8
- https://app.clickup.com/t/8694grcfm
- 8693uttr8
- 8694grcfm
1. Show Patient Id and Patient Code columns in PPS Patient List
2. Allow search by patient Id and Code for PPS Patient List
3. Filter patient search results by ward.
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/5032b376-4275-42fc-8d29-713a76c8a9f1
> PPS Patient id and code columns, search by id and code , filter search results by ward

- src/webapp/components/survey-questions/widgets/DatePickerWidget.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/8694grche
- 8694grche
Use material ui date picker for enhanced user experience
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/71423461-5854-49ca-8a44-6e339443c582
> Use material ui date picker for enhanced user experience

- src/webapp/components/survey-list/table/SurveyListTable.tsx
-   **Issue:** Closes #8694grfg5 [Display facility code in prevalence facility list](https://app.clickup.com/t/8694grfg5)
- Add survey id to facility list column
> Add facility code column to Prevalence Facility List

- src/data/utils/questionHelper.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
-   **Issue:** Closes #? https://app.clickup.com/t/8694hetah
- 8694hetah
1. Fix all add more program rules in pathogen isolates form
2. do not auto populate date so that hideen scetions do not have data
This change needs corresponding metadata changes to program rules which have been done
> Pathogen Iso form data entry fixes.

- src/CompositionRoot.ts
- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/data/utils/surveyFormMappers.ts
- src/domain/repositories/SurveyRepository.ts
- src/domain/usecases/RemoveRepeatableProgramStageUseCase.ts
- src/domain/usecases/SaveFormDataUseCase.ts
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes #?
1. Show "remove" button for all user added wards in facility form on edit.
2. On remove click, remove the repeatable stage event from TEI
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/5c35e303-e4fe-41f3-9ed1-48acb143a407
> remove repeatable ward stage fix

- src/webapp/components/survey-questions/widgets/DatePickerWidget.tsx
- src/webapp/components/survey-questions/widgets/DateTimePickerWidget.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/8694khk0z
- 8694khk0z
1.  use dd-mm-yyy format
> fix: use dd-mm-yyy format

- src/webapp/components/survey-list/SurveyList.tsx
- src/webapp/components/survey-list/SurveyListFilters.tsx
- src/webapp/components/survey-list/hook/useFilteredSurveys.ts
-   **Issue:** Closes #?https://app.clickup.com/t/869446urg
- 869446urg
add status filter for prevalence
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/9d79d726-897f-4ea5-bf84-05f49a760607
>  add status filter for prevalence

- src/data/utils/questionHelper.ts
-   **Issue:** Closes #8694u3qwp  https://app.clickup.com/t/8694u3qwp
1. differentiate between number and integer input types
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/b07014f7-4e2f-4175-8710-2d721da8c747
https://github.com/EyeSeeTea/amr-surveys/assets/83749675/40355b96-c323-42ed-80cb-ceaf64bb1ece
> handle number and integer input types

- src/data/repositories/testRepositories/SurveyFormTestRepository.ts
- src/data/utils/surveyFormMappers.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/SurveySection.tsx
- src/webapp/components/survey/TableSection.tsx
- src/webapp/components/survey/hook/useSurveyForm.ts
- src/webapp/components/survey/hook/useTableSection.ts
-   **Issue:** Closes #? https://app.clickup.com/t/86953e1c3, #86953e1c3
1. Identify Antibiotics Treatment Hospital Episode Section
2. Parse the header row from the questions by grouping 
3. Identify column questions and details questions - all questions are in column except "Please specify Other" on other select
4. Display column questions in column, and Please specify Other as row. 
5. Fix edit bug in Prevalence Mortality forms
https://github.com/user-attachments/assets/8222d465-34ad-4a2d-b95b-269bc4c01e8c
> feat: antibiotics treatment episode as table

- src/domain/usecases/ApplyInitialRulesToSurveyUseCase.ts
-   **Issue:** Closes #? https://app.clickup.com/t/869569t5u, #869569t5u
1. Apply survey rules then program rules.
> fix: apply survey rule then program rule

- src/data/entities/D2Program.ts
- src/data/utils/ruleHelper.ts
- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/domain/entities/Questionnaire/QuestionnaireRules.ts
- src/domain/entities/Questionnaire/QuestionnaireSection.ts
-   **Issue:** Closes #?https://app.clickup.com/t/8695apzfr, #8695apzfr
1. Fix program rules in app for Antimicrobial history section in case report form
2. Apply program rules for Tracked Entity Attributes, which are part of Profile section
> fix: antimicrobial history program rules fix + enabled program rules for Tracked Entity Attributes.

- src/domain/entities/Questionnaire/QuestionnaireRules.ts
- src/webapp/components/survey-list/table/SurveyListTable.tsx
- src/webapp/hooks/useSurveys.ts
-   **Issue:** Closes #? https://app.clickup.com/t/8696quy90, #8696quy90, https://app.clickup.com/t/8696e7430, 8696e7430
1. handle invalid date in date fields where program rules are applicable.
2. Fix white screen error.
> Misc fixes nov24

- src/data/entities/D2Survey.ts
- src/data/repositories/PaginatedSurveyD2Repository.ts
- src/data/repositories/SurveyFormD2Repository.ts
- src/data/utils/questionHelper.ts
- src/data/utils/surveyChildCountHelper.ts
- src/data/utils/surveyListMappers.ts
- src/data/utils/surveyProgramHelper.ts
- src/domain/usecases/GetSurveyUseCase.ts
- src/webapp/hooks/useSurveys.ts
-   **Issue:** Closes #? https://app.clickup.com/t/8696q8g9f, #8696q8g9f
1. Use new tracker program for PPS patient form - create/edit form
2. Use new tracker program for PPS patient form. - list patients , parse name, id and code
3. Search implementation for patient register - by id, by code.
Please ensure complete testing of PPS flow, including creation,edit and list of all survey forms other than just Patient Register is done.
> feat: use new tracker program for PPS patient

- src/domain/usecases/RemoveRepeatableProgramStageUseCase.ts
- src/webapp/components/survey/hook/useSurveyForm.ts
-   **Issue:** Closes https://app.clickup.com/t/8697428va
https://github.com/user-attachments/assets/8113df02-c7f0-4137-bb36-08ef9f708d12
#8697428va
> [bugfix] remove treatment/indication snackbar error 

- src/data/repositories/PaginatedSurveyD2Repository.ts
-   **Issue:** Closes #86980h4az,  https://app.clickup.com/t/86980h4az
1. Spaces in filter give error, suspect this happened post upgrade. Removed any spaces in filters.
> Fix Patient Searches

- src/domain/entities/Questionnaire/Questionnaire.ts
- src/domain/entities/Questionnaire/QuestionnaireQuestion.ts
- src/webapp/components/survey-questions/QuestionWidget.tsx
- src/webapp/components/survey/SurveyForm.tsx
- src/webapp/components/survey/hook/useTreatmentIndicationLink.ts
-   **Issue:** Closes #8696xvx8w,  https://app.clickup.com/t/8696xvx8w?
1. Auto link treatment stage to indication
https://github.com/user-attachments/assets/79628fbd-8b84-4004-b24b-81dd4c9057b9
https://github.com/user-attachments/assets/6892e4a3-e786-4a0e-b9d7-e0d5eec9972d
https://github.com/user-attachments/assets/4310f8a4-cdea-4b3c-a7a0-e48f77506846
https://github.com/user-attachments/assets/9ee94c2f-200b-404e-84b7-91e56da0f32f
https://github.com/user-attachments/assets/4e86f5af-da4c-42e5-b932-81de418037ff
https://github.com/user-attachments/assets/4fe48bf7-6ffa-4b4e-9111-e3ea446bde76
https://github.com/user-attachments/assets/22870946-6d1a-40e6-89a2-894606882f45
> Auto link treatment stage to indication
